// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvfjWBYtOtOgi0-tksaXuEcNcHRqzCLBU',
    appId: '1:585634000848:web:4d0f0177c36aee7a4193d5',
    messagingSenderId: '585634000848',
    projectId: 'creditsea-a574d',
    authDomain: 'creditsea-a574d.firebaseapp.com',
    storageBucket: 'creditsea-a574d.firebasestorage.app',
    measurementId: 'G-16XMCY72SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVxc87ckjnYs_UzB13dN-u9AJxImPewL8',
    appId: '1:585634000848:android:573ec217026483434193d5',
    messagingSenderId: '585634000848',
    projectId: 'creditsea-a574d',
    storageBucket: 'creditsea-a574d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdgqOGoQGyAwIU2Z2Vxn5gaC65onY6QHY',
    appId: '1:585634000848:ios:199749ca175773254193d5',
    messagingSenderId: '585634000848',
    projectId: 'creditsea-a574d',
    storageBucket: 'creditsea-a574d.firebasestorage.app',
    iosBundleId: 'com.example.creditsea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdgqOGoQGyAwIU2Z2Vxn5gaC65onY6QHY',
    appId: '1:585634000848:ios:199749ca175773254193d5',
    messagingSenderId: '585634000848',
    projectId: 'creditsea-a574d',
    storageBucket: 'creditsea-a574d.firebasestorage.app',
    iosBundleId: 'com.example.creditsea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvfjWBYtOtOgi0-tksaXuEcNcHRqzCLBU',
    appId: '1:585634000848:web:4fbcfda048870d494193d5',
    messagingSenderId: '585634000848',
    projectId: 'creditsea-a574d',
    authDomain: 'creditsea-a574d.firebaseapp.com',
    storageBucket: 'creditsea-a574d.firebasestorage.app',
    measurementId: 'G-5PWKKHM27D',
  );
}
